#!/bin/sh

# start picom compositor
picom &
# run kb remap script
remaps &
# set wallpaper, colorschemes. runs wal, dunst
setbg &
# run sxhkd
sxhkdreload &
# run ~/.config/autostart/*.desktop
dex -a &
# # run redshift
~/.config/redshift/launch.sh &
# wmname fix for IDEA
export AWT_TOOLKIT="MToolkit wmname LG3D"
export _JAVA_AWT_WM_NONREPARENTING=1

