#!/usr/bin/env bash

# start picom compositor
picom --experimental-backends --backend glx --xrender-sync-fence &

# run kb remap script
remaps &

# set wallpaper, colorschemes with wal
setbg &

sxhkd &
dunst &
redshift &

# run ~/.config/autostart/*.desktop
dex -a &

# run greenclip clipboard daemon 
greenclip daemon &

# wmname fix for IDEA
export AWT_TOOLKIT="MToolkit wmname LG3D"
export _JAVA_AWT_WM_NONREPARENTING=1

