#!/usr/bin/env bash

export ILRE_DB="ilre"
export ILRE_DB_PORT="5443"
export ILRE_DB_HOSTNAME="localhost"
export ILRE_DB_USERNAME="postgres"
export ILRE_DB_PASSWORD="postgres"

export QGIS_PLUGIN_USE_DEBUGGER="pydevd"

qgis --profile ilredev --globalsettingsfile /home/mikael/git/ilre/settings.ini
