#!/bin/sh

export PGDATABASE="kipudev01"
export PGPORT=5432
export PGHOST="localhost"
export PGSSLMODE="disable"
export QGIS_PLUGIN_USE_DEBUGGER="pydevd"
export KIPU_SKIP_KOMU="true"

qgis --profile kipu
