#!/bin/sh

export PGDATABASE="kipudev01"
export PGPORT=5432
export PGHOST="localhost"
export PGSSLMODE="disable"
export PGUSER="postgres"
export PGPASSWORD="postgres"
export QGIS_PLUGIN_USE_DEBUGGER="pydevd"
export KIPU_SKIP_KOMU="true"
# export QGIS_PLUGINPATH="/home/mikael/.local/share/QGIS/QGIS3/profiles/kipu/python/plugins/kipu-qgis-plugin/src"

qgis --profile kipu
